# Generated by Django 2.0 on 2018-04-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='random_number',
            field=models.IntegerField(default=40),
        ),
    ]
